Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/EachWithObject:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false